{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"Deep_steganography.ipynb","provenance":[],"collapsed_sections":[],"authorship_tag":"ABX9TyOQvSQ97RBn7+jgzcS6BoGK"},"kernelspec":{"name":"python3","display_name":"Python 3"},"accelerator":"GPU"},"cells":[{"cell_type":"code","metadata":{"id":"m0w9ooP0GQGo","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":122},"executionInfo":{"status":"ok","timestamp":1599395922815,"user_tz":-360,"elapsed":43101,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"43bbf0d9-55a3-4e95-e629-42eca40182a5"},"source":["from google.colab import drive\n","drive.mount('/content/drive')"],"execution_count":1,"outputs":[{"output_type":"stream","text":["Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code\n","\n","Enter your authorization code:\n","··········\n","Mounted at /content/drive\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"GcVsqsOabhG3","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1599395996319,"user_tz":-360,"elapsed":1177,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"8a03925f-b02e-40e4-b329-12b05345959a"},"source":["cd /content/drive/My\\ Drive/code"],"execution_count":2,"outputs":[{"output_type":"stream","text":["/content/drive/My Drive/code\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"ULrUJB8vbW6p","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":119},"executionInfo":{"status":"ok","timestamp":1599396013452,"user_tz":-360,"elapsed":13393,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"205dc862-a269-4fa2-d623-af14d66b45b0"},"source":["!git clone https://github.com/alexandremuzio/deep-steg.git"],"execution_count":3,"outputs":[{"output_type":"stream","text":["Cloning into 'deep-steg'...\n","remote: Enumerating objects: 114, done.\u001b[K\n","remote: Total 114 (delta 0), reused 0 (delta 0), pack-reused 114\u001b[K\n","Receiving objects: 100% (114/114), 108.13 MiB | 12.56 MiB/s, done.\n","Resolving deltas: 100% (41/41), done.\n","Checking out files: 100% (23/23), done.\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"tW8msAiXIJ_t","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":35},"executionInfo":{"status":"ok","timestamp":1598721162835,"user_tz":-360,"elapsed":1281,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"074251e2-789f-4031-f272-d8ab11a0d1f2"},"source":["import numpy as np\n","\n","def mse(imageA, imageB):\n","\t# the 'Mean Squared Error' between the two images is the\n","\t# sum of the squared difference between the two images;\n","\t# NOTE: the two images must have the same dimension\n","\terr = np.sum((imageA.astype(\"float\") - imageB.astype(\"float\")) ** 2)\n","\terr /= float(imageA.shape[0] * imageA.shape[1])\n","\tarr = ((imageA-imageB)**2).reshape(64*64*3)\n","\t# return the MSE, the lower the error, the more \"similar\"\n","\t# the two images are\n","\treturn arr\n","\n","imageA = np.random.rand(64,64,3)\n","imageB = np.random.rand(64,64,3)\n","print(np.concatenate([mse(imageA,imageB),np.array([1,2,3])]))\n","\n","\n"],"execution_count":null,"outputs":[{"output_type":"stream","text":["[0.14185572 0.18469359 0.15826179 ... 1.         2.         3.        ]\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"-xvlo3fjfhrx","colab_type":"text"},"source":["Install Wget to download the tiny imagenet dataset\n"]},{"cell_type":"code","metadata":{"id":"BmEizTGPe1Iu","colab_type":"code","colab":{}},"source":["!pip install wget"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"-JoI--KAfsYn","colab_type":"text"},"source":["Download Tiny Imagenet\n"]},{"cell_type":"code","metadata":{"id":"Dl7fzFgbf4K7","colab_type":"code","colab":{}},"source":["import wget\n","\n","print('Beginning file download with wget module')\n","\n","url = 'http://www.image-net.org/image/tiny/tiny-imagenet-200.zip'\n","wget.download(url, '/content/drive/My Drive/data/tiny-imagenet-200.zip')"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"ZfqlepAJg8Zj","colab_type":"text"},"source":["Unzip tiny-imagenet-200.zip\n"]},{"cell_type":"code","metadata":{"id":"0L9Xy7U9g7Zy","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":35},"executionInfo":{"status":"ok","timestamp":1598545693929,"user_tz":-360,"elapsed":1830,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"34698e2e-e78f-41ca-c44e-43f7fa6beb98"},"source":["cd /content/drive/My\\ Drive/temp\n"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/drive/My Drive/temp\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"prxbUpeMoFeB","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":35},"executionInfo":{"status":"ok","timestamp":1598545698355,"user_tz":-360,"elapsed":2945,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"709ee698-dd2a-4f27-ec49-09935d97107f"},"source":["!ls"],"execution_count":null,"outputs":[{"output_type":"stream","text":["'Copy of tiny-imagenet-200.zip'\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"_1SPzN7Atbvh","colab_type":"code","colab":{}},"source":["!apt-get install p7zip-full\n","!7za x FileName"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"WYmcDYlooIUz","colab_type":"code","colab":{}},"source":["import zipfile\n","zip_ref = zipfile.ZipFile(\"Copy of tiny-imagenet-200.zip\", 'r')\n","zip_ref.extractall()\n","zip_ref.close()"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"ktouIS7_1OeT","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1598542827681,"user_tz":-360,"elapsed":4270,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"1bf6b7de-cb8f-454b-c08b-792709566ec2"},"source":["!unzip -q tiny-imagenet-200.zip && ls tiny-imagenet-200"],"execution_count":null,"outputs":[{"output_type":"stream","text":["replace tiny-imagenet-200/words.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: "],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"41zLSWEYH4hy","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":894},"executionInfo":{"status":"error","timestamp":1598523346983,"user_tz":-360,"elapsed":1370,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"c9e240f6-6d55-4ef6-fb95-c2700f3b626d"},"source":["cd /content/drive/My\\ Drive/code"],"execution_count":null,"outputs":[{"output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"],"name":"stderr"},{"output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py\", line 2882, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-42-5193a1d04bfe>\", line 1, in <module>\n","    get_ipython().magic('cd /content/drive/My\\\\ Drive/code')\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py\", line 2160, in magic\n","    return self.run_line_magic(magic_name, magic_arg_s)\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py\", line 2081, in run_line_magic\n","    result = fn(*args,**kwargs)\n","  File \"<decorator-gen-91>\", line 2, in cd\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/magic.py\", line 188, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/magics/osm.py\", line 288, in cd\n","    oldcwd = py3compat.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py\", line 1823, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py\", line 1132, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py\", line 313, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py\", line 358, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.6/inspect.py\", line 1448, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.6/inspect.py\", line 696, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.6/inspect.py\", line 725, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.6/inspect.py\", line 709, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.6/posixpath.py\", line 383, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"],"name":"stdout"},{"output_type":"error","ename":"OSError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m"]}]},{"cell_type":"code","metadata":{"id":"hWPnFpL4HKAF","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":90},"executionInfo":{"status":"ok","timestamp":1598115974077,"user_tz":-360,"elapsed":4032,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"6f6b9741-6065-401e-8109-4144acb286de"},"source":["!git clone https://github.com/tuanphan09/deep-steganography.git"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Cloning into 'deep-steganography'...\n","remote: Enumerating objects: 18, done.\u001b[K\n","remote: Total 18 (delta 0), reused 0 (delta 0), pack-reused 18\u001b[K\n","Unpacking objects:   5% (1/18)   \rUnpacking objects:  11% (2/18)   \rUnpacking objects:  16% (3/18)   \rUnpacking objects:  22% (4/18)   \rUnpacking objects:  27% (5/18)   \rUnpacking objects:  33% (6/18)   \rUnpacking objects:  38% (7/18)   \rUnpacking objects:  44% (8/18)   \rUnpacking objects:  50% (9/18)   \rUnpacking objects:  55% (10/18)   \rUnpacking objects:  61% (11/18)   \rUnpacking objects:  66% (12/18)   \rUnpacking objects:  72% (13/18)   \rUnpacking objects:  77% (14/18)   \rUnpacking objects:  83% (15/18)   \rUnpacking objects:  88% (16/18)   \rUnpacking objects:  94% (17/18)   \rUnpacking objects: 100% (18/18)   \rUnpacking objects: 100% (18/18), done.\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"NWDw3NelNaq8","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":894},"executionInfo":{"status":"error","timestamp":1598523285212,"user_tz":-360,"elapsed":1361,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"18889b24-22ed-41cc-d2b3-b53d0c48f35f"},"source":["cd deep-steganography/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"],"name":"stderr"},{"output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py\", line 2882, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-39-1f47dbc21986>\", line 1, in <module>\n","    get_ipython().magic('cd deep-steganography/')\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py\", line 2160, in magic\n","    return self.run_line_magic(magic_name, magic_arg_s)\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py\", line 2081, in run_line_magic\n","    result = fn(*args,**kwargs)\n","  File \"<decorator-gen-91>\", line 2, in cd\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/magic.py\", line 188, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/magics/osm.py\", line 288, in cd\n","    oldcwd = py3compat.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py\", line 1823, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py\", line 1132, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py\", line 313, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py\", line 358, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.6/inspect.py\", line 1448, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.6/inspect.py\", line 696, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.6/inspect.py\", line 725, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.6/inspect.py\", line 709, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.6/posixpath.py\", line 383, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"],"name":"stdout"},{"output_type":"error","ename":"OSError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m"]}]},{"cell_type":"code","metadata":{"id":"JdCEXIIYNfxj","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":54},"executionInfo":{"status":"ok","timestamp":1598521314014,"user_tz":-360,"elapsed":4449,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"8b4698e3-9c75-4170-849d-df040e899da1"},"source":["!python dataset.py"],"execution_count":null,"outputs":[{"output_type":"stream","text":["2020-08-27 09:41:50.608550: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"bap2EX9iOOkk","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":83},"outputId":"a36c7c03-acca-4acf-c3ed-9b8b5acaa023"},"source":["!python model.py"],"execution_count":null,"outputs":[{"output_type":"stream","text":["2020-08-27 09:41:54.570184: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"fCnE4BdFPMJc","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":85},"executionInfo":{"status":"ok","timestamp":1598521306823,"user_tz":-360,"elapsed":1502,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"6c1051d3-4d7e-472c-9422-26fb614cd408"},"source":["!python train.py"],"execution_count":null,"outputs":[{"output_type":"stream","text":["  File \"train.py\", line 89\n","    model_file = \"(\"/content/drive/My Drive/code/models/CNN/weights-{epoch:02d}-{val_loss:.2f}.hdf5\"\n","                                          ^\n","SyntaxError: invalid syntax\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"RoFYr5UxlCEL","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":892},"executionInfo":{"status":"ok","timestamp":1598123795289,"user_tz":-360,"elapsed":7262,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"fd769112-cd16-4f65-c2cd-1becf9b9a9a6"},"source":["!python predict.py"],"execution_count":null,"outputs":[{"output_type":"stream","text":["2020-08-22 19:16:31.037534: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1\n","2020-08-22 19:16:32.540115: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300000000 Hz\n","2020-08-22 19:16:32.540375: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2672bc0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-08-22 19:16:32.540411: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-08-22 19:16:32.542662: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1\n","2020-08-22 19:16:32.614025: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-08-22 19:16:32.614944: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2672d80 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n","2020-08-22 19:16:32.615072: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7\n","2020-08-22 19:16:32.615421: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-08-22 19:16:32.616142: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla K80 computeCapability: 3.7\n","coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s\n","2020-08-22 19:16:32.616227: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1\n","2020-08-22 19:16:32.618311: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10\n","2020-08-22 19:16:32.620414: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10\n","2020-08-22 19:16:32.620815: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10\n","2020-08-22 19:16:32.622999: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10\n","2020-08-22 19:16:32.624348: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10\n","2020-08-22 19:16:32.628452: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7\n","2020-08-22 19:16:32.628613: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-08-22 19:16:32.629399: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-08-22 19:16:32.630102: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0\n","2020-08-22 19:16:32.630175: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1\n","2020-08-22 19:16:33.117865: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:\n","2020-08-22 19:16:33.117950: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 \n","2020-08-22 19:16:33.117970: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N \n","2020-08-22 19:16:33.118242: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-08-22 19:16:33.119102: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-08-22 19:16:33.119899: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10629 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)\n","Traceback (most recent call last):\n","  File \"predict.py\", line 48, in <module>\n","    list_files = get_file()\n","  File \"predict.py\", line 39, in get_file\n","    data = pd.read_csv('shape.csv')\n","  File \"/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py\", line 676, in parser_f\n","    return _read(filepath_or_buffer, kwds)\n","  File \"/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py\", line 448, in _read\n","    parser = TextFileReader(fp_or_buf, **kwds)\n","  File \"/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py\", line 880, in __init__\n","    self._make_engine(self.engine)\n","  File \"/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py\", line 1114, in _make_engine\n","    self._engine = CParserWrapper(self.f, **self.options)\n","  File \"/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py\", line 1891, in __init__\n","    self._reader = parsers.TextReader(src, **kwds)\n","  File \"pandas/_libs/parsers.pyx\", line 374, in pandas._libs.parsers.TextReader.__cinit__\n","  File \"pandas/_libs/parsers.pyx\", line 674, in pandas._libs.parsers.TextReader._setup_parser_source\n","FileNotFoundError: [Errno 2] File shape.csv does not exist: 'shape.csv'\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"Oo5ILSVNnfCN","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":108},"executionInfo":{"status":"ok","timestamp":1598124085623,"user_tz":-360,"elapsed":5660,"user":{"displayName":"Deep Steganography","photoUrl":"","userId":"17444086891419800955"}},"outputId":"c6d2ca8d-6c36-4540-dce3-cef63f28a756"},"source":["!python statistic.py"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Traceback (most recent call last):\n","  File \"statistic.py\", line 52, in <module>\n","    new_img = cv2.resize(img, (100, 200))\n","cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'resize'\n","\n"],"name":"stdout"}]}]}